### ISSUE TITLE
Inappropriate use of the arduino-library topic

### ISSUE THREAD

**Issue by per1234** [naufalboys/Project_RFID_SD#1]
This repository is an Arduino sketch, not an Arduino library, thus the use of the `arduino-library` topic is inappropriate.

The topic can be removed by clicking the "Manage topics" link near the top of the repository's home page and then clicking the **X** to the right of `arduino-library`. I suggest adding the [`arduino-sketch`](https://github.com/topics/arduino-sketch) topic instead.

**Comment by naufalboys** [comment]
okaay, thank you for reminding me :)

**Comment by per1234** [comment]
Thanks @naufalboys!
